version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24

volumes:
  vol_traefik: {}
  vol_taigadb: {}
  vol_taigafront: {}
  vol_taigaback_conf: {}
  vol_taigaback_media: {}

services:

  taigadb:
    env_file: taiga.env
    image: postgres
    restart: unless-stopped
    volumes:
      - vol_taigadb:/var/lib/postgresql/data

  taigarabbit:
    env_file: taiga.env
    restart: unless-stopped
    image: dockertaiga/rabbit

  taigafront:
    env_file: taiga.env
    restart: unless-stopped
    image: dockertaiga/front
    volumes:
      - vol_taigafront:/taiga-conf

  taigaevents:
    env_file: taiga.env
    restart: unless-stopped
    image: dockertaiga/events
    depends_on:
      - taigarabbit
    expose:
      - ${BACKEND_PORT}
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${BACKEND_DOMAIN}
      - traefik.frontend.rule=Host:${BACKEND_DOMAIN}


  taigaback:
    env_file: taiga.env
    restart: unless-stopped
    image: dockertaiga/back
    depends_on:
      - taigadb
      - taigaevents
    volumes:
      - vol_taigaback_conf:/taiga-conf
      - vol_taigaback_media:/taiga-media

  traefik:
    env_file: .env
    build: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_traefik:/etc/traefik/acme/ # Defined in traefik/traefik.toml
    ports:
      - 0.0.0.0:80:80
