version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24

volumes:
  vol_traefik: {}
  vol_gogs_db_data: {}
  vol_gogs_data: {}
  vol_gogs_repos: {}
  vol_drone_db_data: {}
  vol_drone_data: {}

services:

  gogs_db:
    # image: postgres:9.1
    env_file: .env
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - vol_gogs_db_data:/var/lib/postgresql/data/

  gogs:
    env_file: .env
    image: gogs/gogs:latest
    depends_on:
      - gogs_db
    expose:
      - 3000
      # I need to find a way to somehow expose posrt 22 through traefik
      # - 10022:22
    volumes:
      - vol_gogs_data:/data
      - vol_gogs_repos:/home/git/gogs-repositories
    labels:
      - traefik.port=3000
      - traefik.enable=true
      - traefik.backend.domain=${GOGS_DOMAIN}
      - traefik.frontend.rule=Host:${GOGS_DOMAIN}

  drone_db:
    env_file: .env
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - vol_drone_db_data:/var/lib/postgresql/data/

  drone:
    env_file: .env
    image: drone/drone:latest
    depends_on:
      - drone_db
    expose:
      - 8000
    volumes:
      - vol_drone_data:/var/lib/drone
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${DRONE_DOMAIN}
      - traefik.frontend.rule=Host:${DRONE_DOMAIN}

  drone_agent:
    # image: drone/drone:0.7
    env_file: .env
    image: drone/drone:latest
    command: agent
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    env_file: .env
    build: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_traefik:/etc/traefik/acme/ # Defined in traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
