version: '3'

# networks is required because of OpenVPN Client problem
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24

volumes:
  vol_traefik: {}
  vol_gogs_db_data: {}
  vol_gogs_data: {}
  vol_drone_db_data: {}
  vol_drone_data: {}
  vol_odoo_data: {}
  vol_odoo_db_data: {}

services:

  gogs_db:
    env_file: .env
    restart: always
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - vol_gogs_db_data:/var/lib/postgresql/data/

  gogs:
    env_file: .env
    restart: always
    image: gogs/gogs:latest
    depends_on:
      - gogs_db
    expose:
      - ${GOGS_PORT}
    volumes:
      - vol_gogs_data:/data
    labels:
      - traefik.port=3000
      - traefik.enable=true
      - traefik.backend.domain=${GOGS_DOMAIN}
      - traefik.frontend.rule=Host:${GOGS_DOMAIN}

  drone_db:
    env_file: .env
    restart: always
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - vol_drone_db_data:/var/lib/postgresql/data/

  drone:
    env_file: .env
    restart: always
    image: drone/drone:latest
    depends_on:
      - drone_db
      - gogs
    expose:
      - ${DRONE_PORT}
    environment:
      - DRONE_GOGS_SERVER=http://gogs:${GOGS_PORT}
    volumes:
      - vol_drone_data:/var/lib/drone
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${DRONE_SERVER_HOST}
      - traefik.frontend.rule=Host:${DRONE_SERVER_HOST}

  drone_runner:
    env_file: .env
    restart: always
    image: drone/drone-runner-docker:latest
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  odoo_db:
    env_file: .env
    restart: always
    image: postgres:latest
    ports:
      - 5432
    environment:
      - POSTGRES_DB=postgres
    volumes:
      - vol_odoo_db_data:/var/lib/postgresql/data/

  odoo:
    image: odoo:latest
    depends_on:
      - odoo_db
    expose:
      - ${ODOO_PORT}
    environment:
      - HOST=odoo_db
      - USER=$POSTGRES_USER
      - PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - vol_odoo_data:/var/lib/odoo
      # - ./config:/etc/odoo
      # - ./addons:/mnt/extra-addons
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${ODOO_HOST}
      - traefik.frontend.rule=Host:${ODOO_HOST}

  traefik:
    env_file: .env
    restart: always
    build: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_traefik:/etc/traefik/acme/ # Defined in traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
