version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24

volumes:
  vol_traefik: {}
  vol_gogs_db_data: {}
  vol_gogs_data: {}
  vol_drone_db_data: {}
  vol_drone_data: {}

services:

  gogs_db:
    env_file: .env
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - vol_gogs_db_data:/var/lib/postgresql/data/

  gogs:
    env_file: .env
    image: gogs/gogs:latest
    depends_on:
      - gogs_db
    expose:
      - 3000
    volumes:
      - vol_gogs_data:/data
    labels:
      - traefik.port=3000
      - traefik.enable=true
      - traefik.backend.domain=${GOGS_DOMAIN}
      - traefik.frontend.rule=Host:${GOGS_DOMAIN}

  drone_db:
    env_file: .env
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - vol_drone_db_data:/var/lib/postgresql/data/

  drone:
    env_file: .env
    image: drone/drone:latest
    depends_on:
      - drone_db
      - gogs
    expose:
      - 8000
    volumes:
      - vol_drone_data:/var/lib/drone
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${DRONE_SERVER_HOST}
      - traefik.frontend.rule=Host:${DRONE_SERVER_HOST}

  drone_agent:
    env_file: .env
    image: drone/agent:latest
    depends_on:
      - drone

  drone_runner:
    env_file: .env
    image: drone/drone-runner-docker:latest
    depends_on:
      - drone

  traefik:
    env_file: .env
    build: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_traefik:/etc/traefik/acme/ # Defined in traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
